### ISSUE TITLE
No such thing as gam$data

### ISSUE THREAD

**Issue by cgerv002** [rooperc4/GLMGAMRF#1]
Hello,
I am trying to follow your code to create a delta lognormal GAM model. When I attempt to run the predict.gam.index function I get an error. When I looked into the code for the function I noticed that it calls for pa.gam$data and cpue.gam$data. These gam models don't have a "data" component, so I'm confused as to what the function is trying to reference.

**Comment by rooperc4** [comment]
In the gam statement you should have the control=list(keepData=TRUE) option, as below. This should keep a gam model data object that willbe used by the function.
pa.gam <- gam(gam.pa.form, family = binomial, data = PA.data,control=list(keepData=TRUE))

**Comment by cgerv002** [comment]
Oh boy missed that. Thank you!
